version: '2'
services:
  wallet:
    image: pr3d0x/bitcoin-wallet:gbeta
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bitcoin-wallet
    volumes_from:
    - wallet-data
    environment:
      - ENABLE_WEB_VIEW=yes
      - DISPLAY=unix$DISPLAY
      - DEBUG=yes
    network_mode: host
    # ports:
    #  - "10000:10000"
  wallet-data:
    image: pr3d0x/bitcoin-wallet:gbeta
    container_name: wallet-data
    volumes:
    -  /tmp/.X11-unix:/tmp/.X11-unix
    - /etc/localtime:/etc/localtime:ro
    command: /bin/true
